# Generated by Django 4.2.2 on 2023-09-05 13:01

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('information', models.CharField(max_length=50, null=True)),
                ('website', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('choise', models.CharField(max_length=15, null=True)),
                ('img', models.FileField(upload_to='images/')),
                ('cover', models.FileField(upload_to='images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('photo', models.FileField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=300)),
                ('duration', models.CharField(max_length=50)),
                ('meeting_point', models.CharField(max_length=50)),
                ('transport', models.CharField(max_length=50)),
                ('whats_included', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('extra', models.CharField(max_length=50)),
                ('restriction', models.CharField(max_length=50)),
                ('itinerary', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utesdiq', models.IntegerField(null=True)),
                ('gtesdiq', models.BooleanField(null=True)),
                ('gstatus', models.IntegerField(null=True)),
                ('guide_id', models.IntegerField(null=True)),
                ('guide_photo', models.FileField(null=True, upload_to='images/')),
                ('guide_username', models.CharField(max_length=50, null=True)),
                ('guide_phone', models.CharField(max_length=50, null=True)),
                ('guide_information', models.CharField(max_length=50, null=True)),
                ('guide_cover', models.FileField(null=True, upload_to='images/')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('tur_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.guide')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
