# Generated by Django 4.2.2 on 2023-09-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='posting_date',
        ),
    ]
